"""
FastAPI server — entrypoint for the AI girlfriend chat demo.
Replaces the Telegram bot with HTTP + WebSocket endpoints.
"""

import asyncio
import json
import logging
import time
import base64
from contextlib import asynccontextmanager
from pathlib import Path

import yaml
from fastapi import FastAPI, WebSocket, WebSocketDisconnect, UploadFile, File, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.staticfiles import StaticFiles

from bot.config import (
    SERVER_HOST, SERVER_PORT, CONTENT_DIR, UPLOADS_DIR,
    DEFAULT_USER_ID, PERSONA_FILE_SEXTING, GEMINI_FALLBACK_MODEL,
    PHOTO_UNLOCK_COST,
)
from bot.memory.db import init_db, get_connection
from bot.memory.stm import get_all_messages
from bot.persona import load_persona
from bot.providers.gemini_provider import GeminiProvider
from bot.providers.grok_provider import GrokProvider
from bot.chat_engine import ChatEngine, ChatResponse

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)

# Global chat engine
engine: ChatEngine | None = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Initialize DB and providers on startup."""
    global engine

    logger.info("Initializing database...")
    await init_db()

    logger.info("Loading persona...")
    persona = load_persona(PERSONA_FILE_SEXTING)
    nsfw_persona = persona  # one always-open persona drives everything
    logger.info("Persona loaded: %s", persona.name)

    logger.info("Initializing LLM providers...")
    # Victoria is always-open, so every reply is generated by Grok (nsfw_provider).
    # The Anthropic SFW provider is intentionally not constructed here; it remains
    # available in bot/providers/ if SFW routing is ever reintroduced.
    nsfw_provider = GrokProvider()
    classifier_provider = GeminiProvider()
    # thinking_budget=0 → no "thinking" latency; this provider only writes short
    # replies (suggestions + Grok fallback), so speed matters more than reasoning.
    fallback_provider = GeminiProvider(GEMINI_FALLBACK_MODEL, thinking_budget=0)
    vision_provider = GrokProvider()

    engine = ChatEngine(
        persona=persona,
        nsfw_persona=nsfw_persona,
        nsfw_provider=nsfw_provider,
        classifier_provider=classifier_provider,
        vision_provider=vision_provider,
        fallback_provider=fallback_provider,
    )
    logger.info("Chat engine ready")

    yield

    logger.info("Shutting down")


app = FastAPI(title="AI Girlfriend Chat", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Serve content files if directory exists
CONTENT_DIR.mkdir(parents=True, exist_ok=True)
if Path(CONTENT_DIR).exists():
    app.mount("/content", StaticFiles(directory=str(CONTENT_DIR)), name="content")

# Serve user-uploaded photos (created on first upload; ensure it exists so the
# mount succeeds even before the first photo is sent).
UPLOADS_DIR.mkdir(parents=True, exist_ok=True)
app.mount("/uploads", StaticFiles(directory=str(UPLOADS_DIR)), name="uploads")


# ------------------------------------------------------------------
# REST endpoints
# ------------------------------------------------------------------

# NOTE: The sidebar profile (name, tagline, bio, "about me" grid) is curated
# directly in the frontend (frontend/app/page.tsx -> PROFILE). There is no
# /api/profile endpoint: the persona YAML doesn't carry that presentational copy,
# so the frontend is the single source of truth for profile display.


@app.get("/api/history/{mode}")
async def get_history(mode: str, user_id: int = Query(default=None)):
    """Return chat history for a specific mode. Seeds opening message for new sexting users."""
    user_id = user_id or DEFAULT_USER_ID
    if mode not in ("sexting", "story"):
        return JSONResponse({"error": "Invalid mode"}, status_code=400)

    messages = await get_all_messages(user_id, mode=mode)

    # Seed opening message for new sexting users (Victoria initiates).
    # The opening may contain multiple lines — each becomes its own bubble.
    if mode == "sexting" and not messages and engine:
        from bot.memory.stm import add_message as stm_add
        opening = engine.persona.get_random_opening()
        parts = [p.strip() for p in opening.split("\n") if p.strip()]
        for part in parts:
            await stm_add(user_id, "assistant", part, mode="sexting")
        messages = await get_all_messages(user_id, mode=mode)

    # Seed opening narration for new story users (chapter 1 scene-setter)
    if mode == "story" and not messages and engine:
        from bot.memory.stm import add_message as stm_add
        from bot.config import STORY_FILE
        try:
            with open(str(STORY_FILE), "r", encoding="utf-8") as f:
                story_data = yaml.safe_load(f)
            ch1 = story_data.get("chapters", [{}])[0]
            setting = ch1.get("setting", "")
            first_beat = ch1.get("narrative_beats", [""])[0]
            opening = (
                f"*{setting}*\n\n"
                f"*You push the door open without thinking. And there she is.*\n\n"
                f"{first_beat}"
            )
            await stm_add(user_id, "assistant", opening, mode="story")
            messages = await get_all_messages(user_id, mode=mode)
        except Exception:
            logger.warning("Failed to seed story opening for user %d", user_id, exc_info=True)

    from bot.photo_content import is_photo_unlocked

    out = []
    for m in messages:
        if m["role"] not in ("user", "assistant"):
            continue
        img = m.get("image_url")
        entry = {
            "role": m["role"],
            "content": m["content"],
            "timestamp": m["timestamp"],
            "image_url": img,
        }
        # Her selfies (/content/...) are pay-to-see: locked unless already paid.
        # User uploads (/uploads/...) are never locked.
        if img and img.startswith("/content/"):
            unlocked = await is_photo_unlocked(user_id, img)
            entry["locked"] = not unlocked
            entry["cost"] = PHOTO_UNLOCK_COST
        out.append(entry)

    return {"mode": mode, "messages": out}


@app.get("/api/story/chapter")
async def get_story_chapter(user_id: int = Query(default=None)):
    """Get current story chapter."""
    if not engine:
        return JSONResponse({"error": "Engine not ready"}, status_code=503)
    uid = user_id or DEFAULT_USER_ID
    chapter = await engine.get_story_chapter(uid)
    return {"chapter": chapter}


@app.get("/api/tokens")
async def get_tokens(user_id: int = Query(default=None)):
    """Current token balance (creates the account with the starting grant)."""
    from bot.tokens import get_balance
    uid = user_id or DEFAULT_USER_ID
    return {"balance": await get_balance(uid)}


@app.post("/api/tokens/topup")
async def topup_tokens(user_id: int = Query(default=None)):
    """Demo 'Get more' — grant a fresh batch of tokens."""
    from bot.tokens import top_up
    uid = user_id or DEFAULT_USER_ID
    return {"balance": await top_up(uid)}


@app.post("/api/unlock")
async def unlock_photo(user_id: int = Query(default=None), photo_url: str = Query(...)):
    """Spend PHOTO_UNLOCK_COST tokens to reveal one of Victoria's blurred selfies."""
    from bot.tokens import spend, get_balance
    from bot.photo_content import mark_photo_unlocked
    uid = user_id or DEFAULT_USER_ID

    if not photo_url.startswith("/content/"):
        return JSONResponse({"error": "Not an unlockable photo"}, status_code=400)

    new_balance = await spend(uid, PHOTO_UNLOCK_COST)
    if new_balance is None:
        return JSONResponse(
            {"error": "Not enough tokens", "balance": await get_balance(uid)},
            status_code=402,
        )
    await mark_photo_unlocked(uid, photo_url)
    return {"unlocked": True, "balance": new_balance, "url": photo_url}


@app.post("/api/suggest")
async def suggest_reply(user_id: int = Query(default=None), mode: str = Query(default="sexting")):
    """AI Help — generate a suggested reply for the user to send to Victoria."""
    if not engine:
        return JSONResponse({"error": "Engine not ready"}, status_code=503)
    uid = user_id or DEFAULT_USER_ID
    try:
        suggestion = await engine.suggest_reply(uid, mode=mode)
    except Exception as e:
        logger.warning("Suggest endpoint failed: %s", e)
        suggestion = ""
    return {"suggestion": suggestion}


@app.post("/api/reset")
async def reset_user(user_id: int = Query(default=None)):
    """Wipe all data for a user — messages, memories, intimacy, story progress, facts, engagement."""
    uid = user_id or DEFAULT_USER_ID
    conn = await get_connection()
    try:
        for table in ("messages", "memories", "user_facts", "sent_content",
                      "story_progress", "engagement_state", "intimacy_state",
                      "user_tokens"):
            try:
                await conn.execute(f"DELETE FROM {table} WHERE user_id = ?", (uid,))
            except Exception:
                logger.debug("Reset skipped table %s (may not exist yet)", table, exc_info=True)
        await conn.commit()
        logger.info("Reset all data for user %d", uid)
    finally:
        await conn.close()
    return {"status": "ok", "user_id": uid}


# ------------------------------------------------------------------
# WebSocket chat
# ------------------------------------------------------------------

class ConnectionManager:
    """Track active WebSocket connections."""

    def __init__(self):
        self.active: dict[int, WebSocket] = {}

    async def connect(self, user_id: int, ws: WebSocket):
        await ws.accept()
        self.active[user_id] = ws
        logger.info("WebSocket connected: user %d", user_id)

    def disconnect(self, user_id: int):
        self.active.pop(user_id, None)
        logger.info("WebSocket disconnected: user %d", user_id)

    async def send_json(self, user_id: int, data: dict):
        ws = self.active.get(user_id)
        if ws:
            await ws.send_json(data)


manager = ConnectionManager()


# ------------------------------------------------------------------
# Online-only re-engagement ("double-text" when the user goes quiet
# while still connected). No offline queue, no cron for absent users.
# ------------------------------------------------------------------

IDLE_NUDGE_MIN_SECONDS = 120   # wait 2–4 min before a spontaneous follow-up
IDLE_NUDGE_MAX_SECONDS = 240
MAX_CONSECUTIVE_NUDGES = 1      # at most one nudge, then stay quiet until he writes

idle_tasks: dict[int, asyncio.Task] = {}
nudge_counts: dict[int, int] = {}


def _cancel_idle(user_id: int):
    """Cancel any pending idle-nudge task for a user."""
    task = idle_tasks.pop(user_id, None)
    if task and not task.done():
        task.cancel()


def _schedule_idle_nudge(user_id: int):
    """(Re)start the idle-nudge countdown for a user."""
    _cancel_idle(user_id)
    idle_tasks[user_id] = asyncio.create_task(_idle_nudge_worker(user_id))


async def _idle_nudge_worker(user_id: int):
    """After a quiet gap (still online), send a spontaneous follow-up."""
    import random
    try:
        await asyncio.sleep(random.uniform(IDLE_NUDGE_MIN_SECONDS, IDLE_NUDGE_MAX_SECONDS))

        if user_id not in manager.active or not engine:
            return
        if nudge_counts.get(user_id, 0) >= MAX_CONSECUTIVE_NUDGES:
            return

        response = await engine.generate_reengagement(user_id)
        # User may have come back (and cancelled us) while generating.
        if not response.messages or user_id not in manager.active:
            return

        nudge_counts[user_id] = nudge_counts.get(user_id, 0) + 1
        await _send_response_with_typing(user_id, response, mode="sexting")
        try:
            from bot.engagement import record_reengage
            await record_reengage(user_id)
        except Exception:
            pass

        # Allow one more nudge later if we're still under the cap.
        if nudge_counts.get(user_id, 0) < MAX_CONSECUTIVE_NUDGES:
            _schedule_idle_nudge(user_id)
    except asyncio.CancelledError:
        pass
    except Exception as e:
        logger.warning("Idle nudge failed for user %d: %s", user_id, e)


async def _send_response_with_typing(
    user_id: int,
    response: ChatResponse,
    mode: str,
    fixed_delay: float | None = None,
    bubble_gap: float | None = None,
):
    """Send response messages with typing simulation delays.

    fixed_delay: if set, use this fixed typing pause before EVERY bubble instead
        of the length-scaled delay (used for stories — a steady ~1s beat).
    bubble_gap: if set, use this fixed gap between bubbles instead of the random
        short gap.
    """
    import random

    ws = manager.active.get(user_id)
    if not ws:
        return

    # Nothing to say — make sure the (possibly already-running) typing indicator
    # is cleared so it doesn't get stuck on.
    if not response.messages and not response.content_urls:
        await manager.send_json(user_id, {"type": "typing_end"})
        return

    for i, msg in enumerate(response.messages):
        # Typing indicator
        await manager.send_json(user_id, {"type": "typing_start"})

        if fixed_delay is not None:
            delay = fixed_delay
        else:
            # Typing delay scaled to message length (kept short so she feels snappy)
            length = len(msg)
            if length < 50:
                delay = random.uniform(0.5, 1.1)
            elif length < 150:
                delay = random.uniform(0.9, 1.8)
            else:
                delay = random.uniform(1.5, 2.6)

        await asyncio.sleep(delay)
        await manager.send_json(user_id, {"type": "typing_end"})

        # Send the message
        await manager.send_json(user_id, {
            "type": "message",
            "role": "assistant",
            "content": msg,
            "timestamp": time.time(),
            "mode": mode,
        })

        # Pause between multi-bubble messages
        if i < len(response.messages) - 1:
            gap = bubble_gap if bubble_gap is not None else random.uniform(0.3, 0.7)
            await asyncio.sleep(gap)

    # Send content URLs if any. Victoria's selfies arrive LOCKED (blurred) and
    # cost tokens to unlock; the frontend uses photo_url to call /api/unlock.
    for url in response.content_urls:
        await manager.send_json(user_id, {
            "type": "image",
            "url": url,
            "locked": True,
            "cost": PHOTO_UNLOCK_COST,
            "photo_url": url,
            "timestamp": time.time(),
            "mode": mode,
        })


@app.websocket("/ws/chat")
async def websocket_chat(ws: WebSocket, user_id: int = Query(default=None), user_name: str = Query(default=None)):
    user_id = user_id or DEFAULT_USER_ID
    await manager.connect(user_id, ws)

    # Save user name as a fact (so Victoria knows who she's talking to)
    if user_name:
        from bot.memory.facts import upsert_fact
        await upsert_fact(user_id, "name", user_name)

    try:
        while True:
            raw = await ws.receive_text()
            data = json.loads(raw)

            msg_type = data.get("type", "message")
            mode = data.get("mode", "sexting")
            text = data.get("content", "").strip()

            # Card request (Hear a fantasy / Hear a story): pull from the library.
            if msg_type == "card":
                kind = data.get("kind", "")
                if kind not in ("fantasy", "story"):
                    continue
                _cancel_idle(user_id)
                nudge_counts[user_id] = 0
                logger.info("WS card from user %d: %s", user_id, kind)
                if text:
                    from bot.memory.stm import add_message as stm_add
                    await stm_add(user_id, "user", text, mode="sexting")
                await manager.send_json(user_id, {"type": "typing_start"})
                response = await engine.generate_card(user_id, kind)
                # Stories and fantasies: steady ~1s beat — ~1s before the first
                # bubble and ~1s between each of the (always 3) bubbles.
                await _send_response_with_typing(
                    user_id, response, mode="sexting",
                    fixed_delay=1.0, bubble_gap=0.0,
                )
                _schedule_idle_nudge(user_id)
                continue

            # Handle image uploads via WebSocket (base64)
            image_bytes = None
            if data.get("image"):
                try:
                    image_bytes = base64.b64decode(data["image"])
                except Exception:
                    logger.warning("Failed to decode uploaded image for user %d", user_id, exc_info=True)

            if not text and not image_bytes:
                continue

            # User is active again — cancel any pending idle nudge and reset
            # the consecutive-nudge counter so she can nudge again later.
            _cancel_idle(user_id)
            nudge_counts[user_id] = 0

            logger.info("WS message from user %d [%s]: %s", user_id, mode, (text or "[image]")[:80])

            if mode == "story":
                # Story mode: direct processing, one at a time
                response = await engine.process_message(user_id, text, mode="story", image_bytes=image_bytes)
                await _send_response_with_typing(user_id, response, mode="story")
            else:
                # Sexting mode: batched processing. Start the typing indicator
                # right away so she looks like she's already typing while the
                # debounce window collects his messages.
                await manager.send_json(user_id, {"type": "typing_start"})

                async def on_response(resp: ChatResponse):
                    await _send_response_with_typing(user_id, resp, mode="sexting")
                    # Start the idle countdown once she's done replying.
                    _schedule_idle_nudge(user_id)

                await engine.process_sexting_batched(
                    user_id, text, image_bytes=image_bytes, on_response=on_response
                )

    except WebSocketDisconnect:
        _cancel_idle(user_id)
        nudge_counts.pop(user_id, None)
        manager.disconnect(user_id)
    except Exception as e:
        logger.error("WebSocket error: %s", e, exc_info=True)
        _cancel_idle(user_id)
        nudge_counts.pop(user_id, None)
        manager.disconnect(user_id)


# ------------------------------------------------------------------
# Run
# ------------------------------------------------------------------

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("server.app:app", host=SERVER_HOST, port=SERVER_PORT, reload=True)
    uvicorn.run("server.app:app", host=SERVER_HOST, port=SERVER_PORT, reload=True)
